# Manipulação de Strings com Python

> Uma variável primária de texto é chamada de char ou caracter possibilitando o armazenamento de 8 bit de memória. Quando necessitamos de um conjunto de caracteres utilizamos um objeto, ou variáveis compostas no caso da maioria das linguagens chamada de string. Vamos ver como se aplica.

In [7]:
frase = "Boa tarde a todos"
print(frase)
saudacao = frase[0:9]
print(saudacao)

Boa tarde a todos
Boa tarde


In [6]:
print(type(frase))
print(type(saudacao))

<class 'str'>
<class 'str'>


In [11]:
print(frase.count(' '))
print(saudacao.count(' '))

3
1


In [12]:
print(len(frase))
print(len(saudacao))

17
9


In [20]:
frase = frase.replace('a todos' , 'galerinha!')
print(frase)
saudacao = saudacao.replace('tarde' , 'noite')
print(saudacao)

Boa tarde galerinha!
Boa noite


In [21]:
frase = [i for i in frase]
print(frase)

['B', 'o', 'a', ' ', 't', 'a', 'r', 'd', 'e', ' ', 'g', 'a', 'l', 'e', 'r', 'i', 'n', 'h', 'a', '!']


In [26]:
for x in frase:
    print(x)

B
o
a
 
t
a
r
d
e
 
g
a
l
e
r
i
n
h
a
!


## Exercício 1

> Crie um código para a seguinte frase: "" reparticionado em partes, após isso crie um print format para visualizar cada palavra em uma coluna separada.

In [35]:
exer = ['Sabia','que','o','sábia','sabia','assubiar']
for x in exer:
    print(x)

Sabia
que
o
sábia
sabia
assubiar


In [36]:
frase3 = "sabia que o sabiá sabia assubiar"
palavras = frase3.split()
print(palavras)

['sabia', 'que', 'o', 'sabiá', 'sabia', 'assubiar']


In [44]:
frase3 = "sabia que o sabiá sabia assubiar"
palavras = frase3.split()
print(palavras)

for i in range(max(len(x)for x in palavras)):
    for y in palavras:
        print(y[i] if i < len(y) else ' ', end=' ')
    
    print()

['sabia', 'que', 'o', 'sabiá', 'sabia', 'assubiar']
s q o s s a 
a u   a a s 
b e   b b s 
i     i i u 
a     á a b 
          i 
          a 
          r 


In [46]:
for i in range(max(len(x) for x in palavras)):
    print(' '.join(x[i] if i< len(x) else ' ' for x in palavras))

s q o s s a
a u   a a s
b e   b b s
i     i i u
a     á a b
          i
          a
          r


# Introdução a Numpy

> Numpy é uma biblioteca python para desenvolvimento de matrizes. Tem por objetivo facilitar na criação de algoritmos matematicos para solucionar paradgimas avançados em relação a arrays

In [49]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [50]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [52]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [58]:
print(a.max())
print(b.max())
print(c.max())

3
6
1.0


In [59]:
print(a.sum())
print(b.sum())
print(c.sum())
print(d.sum())

6
21
9.0
5.0


>Para calcular média

In [60]:
print(a.mean())
print(b.mean())
print(c.mean())
print(d.mean())

2.0
3.5
1.0
0.2


> Para desvio de padrão

In [64]:
print(round(a.std(),2))
print(round(b.std(),2))
print(round(c.std(),2))
print(round(d.std(),2))

0.82
1.71
0.0
0.4


In [72]:
e = np.array([])
e.append(1)
print(e)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

# Exercício 2

> Crie uma matriz chamada contar com os números de 0 até 9. Ao final crie uma contagem, média e desvio padrão dessa matriz. Para adicionar de zero a 9 utiize um for e depois atribua à matriz

In [80]:
for x in range(0,9):
    contar = [1,2]
    print = contar[x]
print(contar)

IndexError: list index out of range